import React, { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import api from "../../lib/api";
import DashboardShell from "../../components/DashboardShell";
import StatusBadge from "../../components/StatusBadge";
import Button from "../../components/Button";

const NAV = [{ to: "/admin", label: "Institutions" }, { to: "/admin/onboard", label: "Onboard institution" }];
const ACTIONS = ["institution.onboarded", "institution.status_changed", "institution.wallet_rotated", "institution.deleted", "staff.added", "staff.removed", "staff.admin_granted", "staff.admin_revoked", "certificate.issued", "certificate.bulk_issued", "certificate.revoked", "certificate.reissued", "auth.login_success", "auth.login_failed", "auth.admin_login_success", "auth.admin_login_failed", "audit.viewed", "audit.filtered", "audit.exported"];

export default function AuditLog() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [filters, setFilters] = useState(() => Object.fromEntries(searchParams));
  const [showAuditEvents, setShowAuditEvents] = useState(() => searchParams.get("includeAuditEvents") === "true");
  const [data, setData] = useState({ logs: [], total: 0, page: 1, pages: 1 });
  const [institutions, setInstitutions] = useState([]);
  const [alerts, setAlerts] = useState([]);
  const [expanded, setExpanded] = useState(null);
  const [integrity, setIntegrity] = useState(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { api.get("/institutions").then((res) => setInstitutions(res.data)); api.get("/audit/alerts").then((res) => setAlerts(res.data)); }, []);
  useEffect(() => { load(); }, [searchParams]);
  async function load() { setLoading(true); try { const res = await api.get("/audit", { params: { ...Object.fromEntries(searchParams), includeAuditEvents: searchParams.get("includeAuditEvents") || "false" } }); setData(res.data); } finally { setLoading(false); } }
  function apply(page = 1) { const next = Object.fromEntries(Object.entries({ ...filters, includeAuditEvents: showAuditEvents ? "true" : "false", page }).filter(([, value]) => value)); setSearchParams(next); }
  async function verify() { const res = await api.get("/audit/verify"); setIntegrity(res.data); }
  async function exportCsv() { const res = await api.get("/audit/export", { params: Object.fromEntries(searchParams), responseType: "blob" }); const url = URL.createObjectURL(res.data); const link = document.createElement("a"); link.href = url; link.download = "audit-log.csv"; link.click(); URL.revokeObjectURL(url); }
  return <DashboardShell eyebrow="Platform administration" title="Audit log" subtitle={`${data.total} recorded event${data.total === 1 ? "" : "s"}`} navItems={NAV} actions={<><Button variant="secondary" onClick={exportCsv}>Export CSV</Button><Button onClick={verify}>Verify log integrity</Button></>}>
    {integrity && <p className={`mb-5 rounded border px-4 py-3 text-sm ${integrity.valid ? "border-status-verified/30 bg-status-verified-tint text-status-verified" : "border-status-revoked/30 bg-status-revoked-tint text-status-revoked"}`}>{integrity.valid ? `Integrity verified across ${integrity.checked} entries.` : `Integrity check failed at ${integrity.brokenAt}.`}</p>}
    {alerts.length > 0 && <section className="mb-6 space-y-3"><h2 className="font-display text-lg text-ink">Alerts</h2>{alerts.map((alert, index) => <Link key={`${alert.type}-${index}`} to={`/admin/audit?from=${new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10)}`} className="block rounded border border-status-pending/30 bg-status-pending-tint px-4 py-3 text-sm text-ink"><strong className="capitalize">{alert.type.replaceAll("_", " ")}</strong><span className="ml-2">{alert.message}</span></Link>)}</section>}
    <FilterBar filters={filters} setFilters={setFilters} institutions={institutions} showAuditEvents={showAuditEvents} setShowAuditEvents={setShowAuditEvents} onApply={() => apply()} />
    {loading ? <p className="text-ink-muted">Loading activity…</p> : <AuditTable logs={data.logs} expanded={expanded} setExpanded={setExpanded} />}
    <Pagination data={data} onPage={apply} />
  </DashboardShell>;
}

function FilterBar({ filters, setFilters, institutions, showAuditEvents, setShowAuditEvents, onApply }) { const update = (key, value) => setFilters((old) => ({ ...old, [key]: value })); return <form onSubmit={(e) => { e.preventDefault(); onApply(); }} className="mb-6 grid gap-3 rounded border border-border bg-paper-raised p-4 sm:grid-cols-3"><Input label="From" type="date" value={filters.from || ""} onChange={(v) => update("from", v)} /><Input label="To" type="date" value={filters.to || ""} onChange={(v) => update("to", v)} /><Select label="Action" value={filters.action || ""} onChange={(v) => update("action", v)}><option value="">All actions</option>{["institution", "staff", "certificate", "auth", "audit"].map((group) => <optgroup key={group} label={group}>{ACTIONS.filter((action) => action.startsWith(`${group}.`)).map((action) => <option key={action}>{action}</option>)}</optgroup>)}</Select><Select label="Institution" value={filters.institution || ""} onChange={(v) => update("institution", v)}><option value="">All institutions</option>{institutions.map((institution) => <option key={institution._id} value={institution._id}>{institution.name}</option>)}</Select><Input label="Actor email" value={filters.actorEmail || ""} onChange={(v) => update("actorEmail", v)} /><Select label="Outcome" value={filters.outcome || ""} onChange={(v) => update("outcome", v)}><option value="">All outcomes</option><option value="success">Success</option><option value="failure">Failure</option></Select><label className="flex items-center gap-2 self-end pb-2 text-sm text-ink"><input type="checkbox" checked={showAuditEvents} onChange={(e) => setShowAuditEvents(e.target.checked)} />Show audit-system events</label><Button type="submit" size="sm">Apply filters</Button></form>; }
function Input({ label, type = "text", value, onChange }) { return <label className="block text-sm text-ink-muted">{label}<input type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 h-10 w-full rounded border border-border-strong bg-paper px-3 text-sm text-ink" /></label>; }
function Select({ label, value, onChange, children }) { return <label className="block text-sm text-ink-muted">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 h-10 w-full rounded border border-border-strong bg-paper px-3 text-sm text-ink">{children}</select></label>; }
export function AuditTable({ logs, expanded, setExpanded, institution = true, ip = true }) { return <div className="-mx-4 overflow-x-auto px-4"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-border text-left text-ink-muted"><th className="pb-3">Timestamp</th><th className="pb-3">Actor</th><th className="pb-3">Action</th><th className="pb-3">Target</th>{institution && <th className="pb-3">Institution</th>}{ip && <th className="pb-3">IP</th>}</tr></thead><tbody className="divide-y divide-border">{logs.map((log) => <React.Fragment key={log._id}><tr onClick={() => setExpanded(expanded === log._id ? null : log._id)} className="cursor-pointer hover:bg-paper-raised"><td className="py-3 text-ink-muted">{new Date(log.createdAt).toLocaleString()}</td><td className="py-3"><div>{log.actorEmail || "System"}</div><StatusBadge status="pending" label={log.actorRole || "unknown"} /></td><td className="py-3"><StatusBadge status={log.outcome === "failure" ? "revoked" : "verified"} label={log.action} /></td><td className="py-3 text-ink-muted">{log.targetLabel || "—"}</td>{institution && <td className="py-3 text-ink-muted">{log.institution?.name || "Platform"}</td>}{ip && <td className="py-3 font-mono text-xs text-ink-muted">{log.ip || "—"}</td>}</tr>{expanded === log._id && <tr><td colSpan={ip && institution ? 6 : 4} className="bg-paper-raised px-4 py-3 text-xs text-ink-muted"><strong>Metadata</strong><dl className="mt-2 grid gap-1">{Object.entries(log.metadata || {}).length ? Object.entries(log.metadata || {}).map(([key, value]) => <div key={key}><dt className="inline font-medium text-ink">{key}: </dt><dd className="inline">{typeof value === "object" ? JSON.stringify(value) : String(value)}</dd></div>) : <div>None</div>}</dl></td></tr>}</React.Fragment>)}</tbody></table></div>; }
export function Pagination({ data, onPage }) { return <div className="mt-5 flex items-center justify-between text-sm text-ink-muted"><span>Page {data.page} of {data.pages}</span><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={data.page <= 1} onClick={() => onPage(data.page - 1)}>Previous</Button><Button size="sm" variant="secondary" disabled={data.page >= data.pages} onClick={() => onPage(data.page + 1)}>Next</Button></div></div>; }
