import React, { useEffect, useState } from "react";
import api from "../../lib/api";
import DashboardShell from "../../components/DashboardShell";
import Button from "../../components/Button";
import { AuditTable, Pagination } from "../admin/AuditLog";

const NAV = [{ to: "/institution", label: "Certificates" }, { to: "/institution/issue", label: "Issue new" }, { to: "/institution/bulk-issue", label: "Bulk issue" }];
const ACTIONS = ["staff.added", "staff.removed", "staff.admin_granted", "staff.admin_revoked", "certificate.issued", "certificate.bulk_issued", "certificate.revoked", "certificate.reissued"];
export default function ActivityLog() { const [filters, setFilters] = useState({}); const [data, setData] = useState({ logs: [], total: 0, page: 1, pages: 1 }); const [expanded, setExpanded] = useState(null); const [loading, setLoading] = useState(true); const load = async (page = 1) => { setLoading(true); const params = Object.fromEntries(Object.entries({ ...filters, page }).filter(([, value]) => value)); try { setData((await api.get("/audit", { params })).data); } finally { setLoading(false); } }; useEffect(() => { load(); }, []); return <DashboardShell title="Activity" subtitle={`${data.total} event${data.total === 1 ? "" : "s"} at your institution`} navItems={NAV}><form onSubmit={(e) => { e.preventDefault(); load(); }} className="mb-6 grid gap-3 rounded border border-border bg-paper-raised p-4 sm:grid-cols-3"><label className="text-sm text-ink-muted">From<input type="date" value={filters.from || ""} onChange={(e) => setFilters({ ...filters, from: e.target.value })} className="mt-1 h-10 w-full rounded border border-border-strong bg-paper px-3 text-sm text-ink" /></label><label className="text-sm text-ink-muted">To<input type="date" value={filters.to || ""} onChange={(e) => setFilters({ ...filters, to: e.target.value })} className="mt-1 h-10 w-full rounded border border-border-strong bg-paper px-3 text-sm text-ink" /></label><label className="text-sm text-ink-muted">Action<select value={filters.action || ""} onChange={(e) => setFilters({ ...filters, action: e.target.value })} className="mt-1 h-10 w-full rounded border border-border-strong bg-paper px-3 text-sm text-ink"><option value="">All actions</option>{ACTIONS.map((action) => <option key={action}>{action}</option>)}</select></label><label className="text-sm text-ink-muted">Actor email<input value={filters.actorEmail || ""} onChange={(e) => setFilters({ ...filters, actorEmail: e.target.value })} className="mt-1 h-10 w-full rounded border border-border-strong bg-paper px-3 text-sm text-ink" /></label><Button type="submit" size="sm">Apply filters</Button></form>{loading ? <p className="text-ink-muted">Loading activity…</p> : <AuditTable logs={data.logs} expanded={expanded} setExpanded={setExpanded} institution={false} ip={false} />}<Pagination data={data} onPage={load} /></DashboardShell>; }
